

:_content-type: PROCEDURE
[id="installation-aws-marketplace-automation_{context}"]
= Using automation to deploy OpenShift 4 in the ICMP

Installing the cluster from the marketplace requires that the OpenShift 4 content AMI is launched and available to the OpenShift cluster node.

.Prerequisites

* You configured an AWS account.
* You created an Amazon S3 bucket with the required IAM
link:https://docs.aws.amazon.com/vm-import/latest/userguide/vmie_prereqs.html#vmimport-role[service role].
* You uploaded your {op-system} VMDK file to Amazon S3.
ifdef::openshift-enterprise,openshift-webscale[]
The {op-system} VMDK file must be the highest version that is less than or equal to the {product-title} version you are installing.
endif::[]
* You downloaded the AWS CLI and installed it on your computer. See
link:https://docs.aws.amazon.com/cli/latest/userguide/install-bundle.html[Install the AWS CLI Using the Bundled Installer].

.Procedure

. ssh to the Quay Content instance which will be referred to as the registry
. Export your AWS profile as an environment variable:
+
[source,terminal]
----
$ export AWS_PROFILE=<aws_profile> <1>
----
<1> The AWS profile name that holds your AWS credentials, like `govcloud`.

. Export the region to associate with your custom AMI as an environment
variable:
+
[source,terminal]
----
$ export AWS_DEFAULT_REGION=<aws_region> <1>
----
<1> The AWS region, like `us-iso-east-1`.

. Set the ansible variables
. Change directories to the location of the ansible playbooks
[source,terminal]
----
$ cd /usr/share/openshift4-aws-iso/playbooks/
----
. Generate the installation configuration files
[source,terminal]
----
$ ansible-playbook generate_ignition.yaml
----
[IMPORTANT] 
====
The configuration files contain a 24-hour CA used only during install. Installation of the OpenShift cluster must be completed within 24 hours of generating the configuration files or the cluster resources will need to be cleaned up and the procedure restarted at this step.
====
. Stage the installation configuration files in S3
[source,terminal]
----
$ ansible-playbook stage_ignition.yaml
----
. Deploy the Security Groups and IAM CloudFormation Template
[source,terminal]
----
$ ansible-playbook deploy_security.yaml
----
. Deploy the Infrastructure (LBs and Route53) CloudFormation Template
[source,terminal]
----
$ ansible-playbook deploy_infra.yaml
----
. Deploy the OpenShift bootstrap CloudFormation Template
----
$ ansible-playbook deploy_bootstrap.yaml
----
. Deploy the OpenShift Control Plan CloudFormation Template
----
$ ansible-playbook deploy_control_plane.yaml
----


