:_content-type: PROCEDURE
[id="installation-aws-icmp_postinstall_{context}"]
= Post-Installtion procedures for OpenShift 4 deployed using the AWS IC Marketplace

Installing the cluster from the marketplace requires that the OpenShift 4 content AMI is launched and available to the OpenShift cluster node.

.Prerequisites

* You have deployed an OpenShift 4 cluster using the AWS IC Marketplace offering

.Procedure

. Export your AWS profile as an environment variable:
+
[source,terminal]
----
$ export AWS_PROFILE=<aws_profile> <1>
----
<1> The AWS profile name that holds your AWS credentials, like `govcloud`.

. Export the region to associate with your custom AMI as an environment
variable:
+
[source,terminal]
----
$ export AWS_DEFAULT_REGION=<aws_region> <1>
----
<1> The AWS region, like `us-iso-east-1`.

. Change directories to the location of the ansible playbooks
[source,terminal]
----
$ cd /usr/share/openshift4-aws-iso/playbooks/
----

. Disable the default Operator Hub configuration
[source,terminal]
----
$ oc patch OperatorHub cluster --type json -p '[{"op": "add", "path": "/spec/disableAllDefaultSources", "value": true}]'
----

. Apply the Image Content Source Policy Mapping
[source,terminal]
----
$ oc apply -f /oc-mirror-workspace/results-*/imageContentSourcePolicy.yaml <1>
----
<1> The name of the results directory is a timestamp generated when the AMI is created and cannot be added statically to the documentation.

. Apply the Operator Catalog configuration
[source,terminal]
----
$ oc apply -f /oc-mirror-workspace/results-*/catalogSource-redhat-operator-index.yaml <1>
----
<1> The name of the results directory is a timestamp generated when the AMI is created and cannot be added statically to the documentat
ion.

. Apply release signatures
[source,terminal]
----
$ oc-mirror-workspace/results-*/release-signatures/signature-sha256-*.json <1>
----
<1> The name of the results directory is a timestamp generated when the AMI is created. The signature digest is specific to each release of OpenShift. Neither can be added statically to the documentation.
ion.

. Deploy OpenShift Update Service (OSUS) operator
[source,terminal]
----
$ ansible-playbook deploy_osus.yaml
----
