

:_content-type: PROCEDURE
[id="launching_ocp4_content_ami_{context}"]
= Launching the OpenShift 4 content AMI in AWS

Installing the cluster from the marketplace requires that the OpenShift 4 content AMI is launched and available to the OpenShift cluster node.

.Prerequisites

* You configured an AWS account.
* You created an Amazon S3 bucket with the required IAM
link:https://docs.aws.amazon.com/vm-import/latest/userguide/vmie_prereqs.html#vmimport-role[service role].
* You subscribed to the AWS IC Marketplace offer

.Procedure

. Open the AWS Web Console and login to the account where OpenShift will be installed
. Browse to the EC2 service
. Browse to the available AMIs
. Select the Quay Content AMI from the OpenShift 4 AWS IC Marketplace offering
. Select "Launch an instance of this AMI"
. Enter options for launching the EC2 instance including; VPC, subnet, IAM instance profile, etc...
. Launch the Quay Content AMI for OpenShift
+
This will be known as the registry
+
[IMPORTANT] 
====
When the Content AMI is launched a quay registry will be installed and the OpenShift 4 container image content will be loaded into the Quay registry.
This process can take from 30-60 minutes to complete
==== 
. ssh into the registry as the ec2-user
. Check the the import process has completed
[source,terminal]
----
$ if [ -e /etc/sysconfig/rh-quay-firstboot ]; then echo "Content AMI Import Complete"; fi
----
